[tox]
envlist = py38,py39,py310,py311,py312,py313,py314,pkg
skip_missing_interpreters = true

[testenv]
description = Run the VascX pytest suite.
extras = test
package = editable
changedir = {tox_root}
setenv =
    MPLBACKEND = Agg
commands =
    pytest {posargs}