from __future__ import annotations

import warnings
from functools import cached_property
from pathlib import Path
from typing import Any, Callable, Dict, Optional, Tuple, Union

import cv2
import numpy as np
from matplotlib import pyplot as plt
from rtnls_enface.fundus import Fundus
from rtnls_enface.utils.data_loading import open_binary_mask
from rtnls_enface.utils.image import match_resolution
from typing_extensions import TypeAlias

from vascx.fundus.features.base import LayerFeature, RetinaFeature, VesselsLayerFeature
from vascx.fundus.layer import VesselTreeLayer
from vascx.fundus.vessels_layer import FundusVesselsLayer
from vascx.shared.features import FeatureSet
from vascx.shared.segment import Segment
from vascx.utils import load_av_segmentation

Aggregator: TypeAlias = Callable[[np.ndarray], np.float32]
FeatureType: TypeAlias = Union[VesselTreeLayer, Segment]


class Retina(Fundus):
    # Cache broadcast index grids for per-pixel geometry.
    @cached_property
    def yy_xx(self) -> tuple[np.ndarray, np.ndarray]:
        h, w = self.resolution
        return np.arange(h)[:, None], np.arange(w)[None, :]

    # Cache squared distance from each pixel to the disc center.
    @cached_property
    def disc_center_dist_sq(self) -> Optional[np.ndarray]:
        if self.disc is None:
            return None
        yy, xx = self.yy_xx
        center = self.disc.center_of_mass
        return (yy - center.y) ** 2 + (xx - center.x) ** 2

    # Cache each pixel's angle relative to the disc-to-fovea axis.
    @cached_property
    def disc_fovea_angle_deg(self) -> Optional[np.ndarray]:
        if self.disc is None or self.fovea_location is None:
            return None

        yy, xx = self.yy_xx
        disc_center = self.disc.center_of_mass
        fy, fx = self.fovea_location.tuple
        vy, vx = fy - disc_center.y, fx - disc_center.x
        norm_v = np.hypot(vx, vy) + 1e-6
        dy = yy - disc_center.y
        dx = xx - disc_center.x
        norm_p = np.hypot(dx, dy) + 1e-6
        cosang = (dx * vx + dy * vy) / (norm_p * norm_v)
        cosang = np.clip(cosang, -1.0, 1.0)
        return np.degrees(np.arccos(cosang))

    # Cache the circular fovea exclusion mask reused by sparsity features.
    @cached_property
    def sparsity_fovea_mask(self) -> np.ndarray:
        if self.fovea_location is None or self.disc is None:
            return np.zeros(self.resolution, dtype=bool)

        yy, xx = self.yy_xx
        radius = self.disc_fovea_distance / 6
        return (xx - self.fovea_location.x) ** 2 + (yy - self.fovea_location.y) ** 2 <= radius**2

    @classmethod
    def _target_names_for_feature(cls, feature) -> list[str]:
        if isinstance(feature, RetinaFeature):
            return ["retina"]
        if isinstance(feature, LayerFeature):
            return ["arteries", "veins"]
        if isinstance(feature, VesselsLayerFeature):
            return ["vessels"]
        return []

    @classmethod
    def _register_canonical_name(
        cls, seen: Dict[str, object], name: str, feature
    ) -> bool:
        existing = seen.get(name)
        if existing is None:
            seen[name] = feature
            return False

        raise ValueError(
            f"Duplicate canonical feature name '{name}' generated by "
            f"{existing.__class__.__name__} and {feature.__class__.__name__}"
        )

    @property
    def arteries(self) -> VesselTreeLayer:
        return self.layers["arteries"]

    @property
    def veins(self) -> VesselTreeLayer:
        return self.layers["veins"]

    @property
    def vessels(self) -> FundusVesselsLayer:
        return self.layers["vessels"]

    def set_retina(self, retina):
        self.retina = retina

    def load_annotation(self, fpath: str):
        layers = load_av_segmentation(fpath)
        layers = {
            key: match_resolution(
                mask.astype(np.uint8), self.resolution, cv2.INTER_NEAREST
            ).astype(bool)
            for key, mask in layers.items()
        }

        self.gt = Retina(layers)
        if self.disc is not None:
            self.gt.disc = self.disc

    def dice(self, ignore_disk=True):
        assert self.gt is not None

        res = {}
        for layer in self.layers.keys():
            res[layer] = self.layers[layer].auc(
                self.gt.layers[layer], remove_disk=ignore_disk
            )

        return res

    def calc_features(
        self,
        feature_set: FeatureSet,
        plots_folder: Optional[str] = None,
        raise_on_error: bool = False,
    ):
        all_features = {}
        seen_names: Dict[str, object] = {}
        for feature in feature_set:
            feature_label = feature.__class__.__name__
            if isinstance(feature, RetinaFeature):
                targets = [("retina", self)]
            elif isinstance(feature, LayerFeature):
                targets = [
                    (layer.name, layer) for layer in self.get_layers(VesselTreeLayer)
                ]
            elif isinstance(feature, VesselsLayerFeature):
                targets = [
                    (layer.name, layer) for layer in self.get_layers(FundusVesselsLayer)
                ]
            else:
                continue

            if len(targets) == 0:
                print(f"No targets found on which to compute feature {feature_label}.")

            for target_name, target in targets:
                try:
                    res = feature.compute(target)
                except Exception as e:
                    if raise_on_error:
                        raise RuntimeError(
                            f"Error computing feature {feature_label} on target {target_name} for retina {self.id}"
                        ) from e
                    warnings.warn(
                        f"Error computing feature {feature_label} on target {target_name}: {e}"
                    )
                    res = None

                feature_name = feature.canonical_name(layer_name=target_name)
                self._register_canonical_name(seen_names, feature_name, feature)
                all_features[feature_name] = res

                if (
                    plots_folder is not None and res is not None
                ):  # only save plots if the feature was computed successfully
                    fig, ax = plt.subplots(1, 1, figsize=(8, 8), dpi=300)
                    feature.plot(ax, target)
                    fname_prefix = str(self.id) if self.id is not None else "sample"
                    plot_name = feature.canonical_name(layer_name=target_name)
                    fname = f"{fname_prefix}_{plot_name}.png"
                    fig.savefig(
                        Path(plots_folder) / fname, dpi=200, bbox_inches="tight"
                    )
                    plt.close(fig)

        return all_features

    @classmethod
    def make_feature_display_names(cls, feature_set: FeatureSet) -> Dict[str, str]:
        mapping = {}
        seen_names: Dict[str, object] = {}
        for feature in feature_set:
            targets = cls._target_names_for_feature(feature)

            for target_name in targets:
                full_key = feature.canonical_name(layer_name=target_name)
                cls._register_canonical_name(seen_names, full_key, feature)
                display = feature.display_name(layer_name=target_name)
                mapping[full_key] = display

        return mapping

    def plot(
        self,
        ax=None,
        av=True,
        vessels=False,
        image=True,
        disc=False,
        fovea=False,
        bounds=False,
        **kwargs,
    ):
        if ax is None:
            fig, ax = plt.subplots(1, 1, figsize=(8, 8), dpi=300)
            ax.imshow(np.zeros(self.resolution))
            ax.set_axis_off()

        super().plot(
            ax=ax, image=image, disc=disc, fovea=fovea, bounds=bounds, **kwargs
        )

        if av:
            self.arteries.plot(ax=ax, mask=True, color=(1, 0, 0))
            self.veins.plot(ax=ax, mask=True, color=(0, 0, 1))

        if vessels:
            self.vessels.plot(ax=ax, mask=True, color=(1, 1, 1))

        return ax

    @classmethod
    def from_file(
        cls,
        av_path: Optional[Union[str, Path]] = None,
        vessels_path: Optional[Union[str, Path]] = None,
        disc_path: Optional[Union[str, Path]] = None,
        fundus_path: Optional[Union[str, Path]] = None,
        fovea_location: Tuple[float, float] = None,
        bounds=None,
        threshold=0.5,
        scaling_factor=1,
        id: Any = None,
        **kwargs,
    ):
        # assert av_path is not None or vessels_path is not None, (
        #     "Either av_path or vessels_path must be provided"
        # )

        layers = {}
        if av_path is not None:
            av_layers = load_av_segmentation(av_path, threshold)

            def get_layer_color(layer_name):
                if layer_name == "arteries":
                    return (1, 0, 0)
                elif layer_name == "veins":
                    return (0, 0, 1)
                else:
                    return (1, 1, 1)

            for key, val in av_layers.items():
                layers[key] = VesselTreeLayer(key, val, color=get_layer_color(key))

        if vessels_path is not None:
            layers["vessels"] = FundusVesselsLayer(
                name="vessels", mask=open_binary_mask(vessels_path)
            )

        retina = cls(
            disc_path_or_mask=disc_path,
            fundus_path_or_mask=fundus_path,
            layers=layers,
            fovea_location=fovea_location,
            scaling_factor=scaling_factor,
            bounds=bounds,
            id=id,
        )

        return retina
