from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TYPE_CHECKING, Callable, Dict, Iterable, Optional, Sequence, Tuple

if TYPE_CHECKING:
    from vascx.shared.features import Feature, FeatureSet


class NamingConvention(str, Enum):
    CANONICAL = "canonical"
    RESOLVED = "resolved"


@dataclass(frozen=True)
class NamePart:
    key: str
    tokens: Tuple[str, ...]
    display: str = ""
    annotation: bool = False
    family: bool = False
    always_keep: bool = False
    resolution_scope: Optional[str] = None


@dataclass(frozen=True)
class FeatureName:
    feature_index: int
    target_name: str
    name: str
    display_name: str


def coerce_naming_convention(value: NamingConvention | str) -> NamingConvention:
    if isinstance(value, NamingConvention):
        return value
    try:
        return NamingConvention(value)
    except ValueError as exc:
        choices = ", ".join(item.value for item in NamingConvention)
        raise ValueError(f"Unknown naming convention '{value}'; choose {choices}") from exc


def _join_name_parts(parts: Sequence[NamePart], active_keys: set[str]) -> str:
    return "_".join(
        token
        for part in parts
        if part.key in active_keys
        for token in part.tokens
        if token
    )


def _humanize_token(token: str) -> str:
    return token.replace("_", " ").replace("p", ".").title()


def _join_display_parts(parts: Sequence[NamePart], active_keys: set[str]) -> str:
    main = " ".join(
        part.display
        for part in parts
        if part.key in active_keys and not part.annotation and part.display
    )
    annotations = [
        part.display
        for part in parts
        if part.key in active_keys and part.annotation and part.display
    ]
    main = " ".join(main.split())
    main = main.replace("]  -", "] -")
    if annotations:
        main = f"{main} ({'; '.join(annotations)})" if main else "; ".join(annotations)
    return main


def make_feature_names(
    feature_set: "FeatureSet",
    target_names_for_feature: Callable[["Feature"], Iterable[str]],
    naming: NamingConvention | str = NamingConvention.CANONICAL,
) -> Dict[Tuple[int, str], FeatureName]:
    """Build canonical or feature-set-resolved names for a feature set."""

    convention = coerce_naming_convention(naming)
    records = []
    for feature_index, feature in enumerate(feature_set):
        for target_name in target_names_for_feature(feature):
            parts = tuple(feature.name_parts(layer_name=target_name))
            if not any(part.family for part in parts):
                parts = (
                    NamePart(
                        key=parts[0].key,
                        tokens=parts[0].tokens,
                        display=parts[0].display,
                        annotation=parts[0].annotation,
                        family=True,
                        always_keep=parts[0].always_keep,
                        resolution_scope=parts[0].resolution_scope,
                    ),
                    *parts[1:],
                )
            records.append((feature_index, target_name, feature, parts))

    canonical_names: Dict[str, Tuple[int, Feature]] = {}
    for feature_index, _, feature, parts in records:
        key = _join_name_parts(parts, {part.key for part in parts})
        if key in canonical_names:
            previous = canonical_names[key]
            raise ValueError(
                f"Duplicate canonical feature name '{key}' generated by feature "
                f"indices {previous[0]} and {feature_index}"
            )
        canonical_names[key] = (feature_index, feature)

    active = [{part.key for part in parts} for _, _, _, parts in records]
    if convention == NamingConvention.RESOLVED:
        families: Dict[Tuple[type, Tuple[str, ...]], list[int]] = {}
        for index, (_, _, feature, parts) in enumerate(records):
            family_part = next(part for part in parts if part.family)
            families.setdefault((feature.__class__, family_part.tokens), []).append(index)

        for family_indices in families.values():
            part_keys = []
            for part in records[family_indices[0]][3]:
                if part.key not in part_keys:
                    part_keys.append(part.key)
            for part_key in part_keys:
                part_template = next(
                    part for index in family_indices for part in records[index][3]
                    if part.key == part_key
                )
                if part_template.always_keep:
                    continue

                scopes = [family_indices]
                if part_template.resolution_scope == "grid":
                    grid_groups = {}
                    for index in family_indices:
                        grid_signature = next(
                            (part.tokens for part in records[index][3] if part.key == "grid"),
                            (),
                        )
                        grid_groups.setdefault(grid_signature, []).append(index)
                    scopes = list(grid_groups.values())

                family_part = any(
                    part.key == part_key and part.family
                    for index in family_indices
                    for part in records[index][3]
                )
                if family_part:
                    continue
                for scope_indices in scopes:
                    signatures = {
                        next(
                            (part.tokens for part in records[index][3] if part.key == part_key),
                            (),
                        )
                        for index in scope_indices
                    }
                    if len(signatures) == 1:
                        for index in scope_indices:
                            active[index].discard(part_key)

    def current_names() -> Dict[str, list[int]]:
        grouped: Dict[str, list[int]] = {}
        for index, record in enumerate(records):
            grouped.setdefault(_join_name_parts(record[3], active[index]), []).append(index)
        return grouped

    while True:
        duplicates = [indices for indices in current_names().values() if len(indices) > 1]
        if not duplicates:
            break
        changed = False
        for indices in duplicates:
            candidate_keys = [
                part.key
                for part in records[indices[0]][3]
                if part.key not in active[indices[0]]
            ]
            for part_key in candidate_keys:
                signatures = {
                    next(
                        (part.tokens for part in records[index][3] if part.key == part_key),
                        (),
                    )
                    for index in indices
                }
                if len(signatures) > 1:
                    for index in indices:
                        if any(part.key == part_key for part in records[index][3]):
                            active[index].add(part_key)
                    changed = True
                    break
        if not changed:
            raise ValueError("Resolved feature names are not unique within the feature set")

    result: Dict[Tuple[int, str], FeatureName] = {}
    display_groups: Dict[str, list[Tuple[int, str]]] = {}
    for index, (feature_index, target_name, _, parts) in enumerate(records):
        name = _join_name_parts(parts, active[index])
        display = _join_display_parts(parts, active[index]) or name
        result[(feature_index, target_name)] = FeatureName(
            feature_index=feature_index,
            target_name=target_name,
            name=name,
            display_name=display,
        )
        display_groups.setdefault(display, []).append((feature_index, target_name))

    for display, keys in display_groups.items():
        if len(keys) <= 1:
            continue
        for feature_index, target_name in keys:
            item = result[(feature_index, target_name)]
            result[(feature_index, target_name)] = FeatureName(
                feature_index=feature_index,
                target_name=target_name,
                name=item.name,
                display_name=f"{item.display_name} [{item.name}]",
            )
    return result
